### PR TITLE
add qf_full_text, pf_full_text vars to default request handler

### PR DESCRIPTION
**Pull request by ndushay**
(should have thought of this in #5 - d'oh)

connects to sul-dlss/spotlight#1175

### CODE REVIEW

**Comment by cbeer** [comment]
:+1: I guess we'll want to update https://github.com/sul-dlss/sul_exhibits_template/blob/master/app/controllers/catalog_controller.rb#L201-L207 to use them?

**Comment by ndushay** [comment]
yes - in progress.

**Comment by ndushay** [comment]
mostly trying to figure out a good test to see if config is talking to Solr that has the vars set.

**Comment by cbeer** [comment]
If it's not easy, should we just assume it is set correctly? When it isn't, that seems more like a configuration or deployment issue.

**Comment by ndushay** [comment]
something like this?

```
  it 'has full text in the pull down' do
    visit '/'
    fill_in 'q', with: 'cobbler'
    select 'Full text', from: 'search_field'
    click_button 'search'
    expect(page.status_code).to eq success
  end
```

**Pull request merged**
